CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  pwd TEXT NOT NULL,
  name TEXT
);

CREATE TABLE IF NOT EXISTS page_urls (
  id TEXT PRIMARY KEY,
  url TEXT NOT NULL,
  path TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS notes (
  id TEXT PRIMARY KEY,
  note TEXT NOT NULL,
  "order" INTEGER NOT NULL DEFAULT 0,
  userId TEXT NOT NULL,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
